import React, { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { amount, Draft, fuels, newDraft, Refueling, Station } from './domain'
import { chronological, comparisons, periodTotals, validate } from './calculations'
import { storage } from './storage'
import './styles.css'

const rubles = new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}); const numeric = new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2})
const dateText=(date:string)=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${date}T12:00:00`))
const id=()=>crypto.randomUUID(); const inputNumber=(value:string)=>value===''?undefined:Number(value)
type Screen='home'|'history'|'stats'|'profile'; type Editor={id?:string;draft:Draft}|null
function App(){
 const [records,setRecords]=useState<Refueling[]>([]),[stations,setStations]=useState<Station[]>([]),[ready,setReady]=useState(false),[screen,setScreen]=useState<Screen>('home'),[editor,setEditor]=useState<Editor>(null),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[period,setPeriod]=useState<'week'|'month'|'year'|'custom'>('month'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[stationName,setStationName]=useState(''),[editingStation,setEditingStation]=useState<Station|null>(null); const importRef=useRef<HTMLInputElement>(null)
 const refresh=async()=>{const [r,s]=await Promise.all([storage.refuelings(),storage.stations()]);setRecords(r);setStations(s.sort((a,b)=>a.name.localeCompare(b.name,'ru')))}; useEffect(()=>{storage.migrateLegacy().then(refresh).then(()=>setReady(true)).catch(()=>setNotice('Не удалось открыть локальное хранилище.'))},[])
 const sorted=useMemo(()=>chronological(records).reverse(),[records]); const comparison=useMemo(()=>comparisons(records),[records]); const latestMileage=useMemo(()=>chronological(records).filter(x=>x.mileage!==undefined).at(-1)?.mileage,[records]); const month=useMemo(()=>{const now=new Date();return records.filter(x=>{const d=new Date(x.date+'T12:00:00');return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()})},[records]); const monthly=periodTotals(month)
 const filteredHistory=useMemo(()=>sorted.filter(x=>`${x.station} ${x.fuelType} ${x.date}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())),[sorted,search])
 const chosen=useMemo(()=>{const now=new Date();if(period==='custom'){if(start&&end&&end<start)return [];return records.filter(x=>(!start||x.date>=start)&&(!end||x.date<=end))}let from=new Date(now);if(period==='week')from.setDate(now.getDate()-6);if(period==='month')from.setDate(1);if(period==='year')from.setMonth(0,1);const key=from.toISOString().slice(0,10);return records.filter(x=>x.date>=key&&x.date<=now.toISOString().slice(0,10))},[records,period,start,end]); const totals=periodTotals(chosen)
 const show=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(''),3000)}; const save=async(e:FormEvent)=>{e.preventDefault();if(!editor)return;const previous=chronological(records.filter(x=>x.id!==editor.id&&x.date<=editor.draft.date&&x.mileage!==undefined)).at(-1)?.mileage;const error=validate(editor.draft,previous);if(error){show(error);return}const now=Date.now();const record:Refueling={...editor.draft,id:editor.id||id(),createdAt:editor.id?records.find(x=>x.id===editor.id)?.createdAt||now:now,updatedAt:now};await storage.saveRefueling(record);if(record.station.trim()&&!stations.some(x=>x.name.localeCompare(record.station.trim(),'ru',{sensitivity:'accent'})===0))await storage.saveStation({id:id(),name:record.station.trim()});await refresh();setEditor(null);show(editor.id?'Заправка изменена.':'Заправка добавлена.')}
 const remove=async(record:Refueling)=>{if(!confirm('Удалить эту заправку?'))return;await storage.deleteRefueling(record.id);await refresh();setEditor(null);show('Заправка удалена.')}
 const saveStation=async()=>{const name=stationName.trim();if(!name){show('Введите название АЗС.');return}if(stations.some(x=>x.id!==editingStation?.id&&x.name.localeCompare(name,'ru',{sensitivity:'accent'})===0)){show('Такая АЗС уже есть.');return}const station={id:editingStation?.id||id(),name};await storage.saveStation(station);setStationName('');setEditingStation(null);await refresh();show('Список АЗС обновлён.')}
 const exportBackup=async()=>{const file=new Blob([JSON.stringify(await storage.backup(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=`toplivo-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}; const importBackup=async(file?:File)=>{if(!file)return;try{await storage.restore(JSON.parse(await file.text()));await refresh();show('Резервная копия восстановлена.')}catch{show('Не удалось восстановить резервную копию.')}}
 if(!ready)return <main className="loading">Загрузка данных…</main>
 return <main><header><div><p className="eyebrow">Личный учёт</p><h1>{({home:'Топливный учёт',history:'История',stats:'Статистика',profile:'Профиль'})[screen]}</h1></div><button className="icon-button" onClick={()=>setScreen('profile')} aria-label="Открыть профиль">⚙</button></header>
 {screen==='home'&&<><section className="summary"><p>Текущий месяц</p><strong>{rubles.format(monthly.totalAmount)}</strong><div><span>{numeric.format(monthly.totalLiters)} л</span><span>{monthly.consumption?`${numeric.format(monthly.consumption)} л/100 км`:'Расход: недостаточно данных'}</span></div></section><section className="section-title"><h2>Последние заправки</h2><button className="text-button" onClick={()=>setScreen('history')}>Все</button></section>{sorted.length?<div className="list">{sorted.slice(0,5).map(x=><FuelCard key={x.id} item={x} comparison={comparison.get(x.id)} onClick={()=>setEditor({id:x.id,draft:{...x}})}/>)}</div>:<Empty onAdd={()=>setEditor({draft:newDraft()})}/>}</>}
 {screen==='history'&&<><label className="search">Поиск<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="АЗС, топливо или дата"/></label><p className="subtext">Найдено: {filteredHistory.length}</p><div className="list">{filteredHistory.map(x=><FuelCard key={x.id} item={x} comparison={comparison.get(x.id)} onClick={()=>setEditor({id:x.id,draft:{...x}})}/>)}</div>{!filteredHistory.length&&<p className="empty-inline">Нет подходящих записей.</p>}</>}
 {screen==='stats'&&<><div className="filters">{(['week','month','year','custom'] as const).map(x=><button key={x} className={period===x?'active':''} onClick={()=>setPeriod(x)}>{({week:'Неделя',month:'Месяц',year:'Год',custom:'Период'})[x]}</button>)}</div>{period==='custom'&&<div className="dates"><label>С<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>По<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>}{start&&end&&end<start?<p className="error">Дата окончания не может быть раньше даты начала.</p>:<><section className="metric-grid"><Metric label="Расходы" value={rubles.format(totals.totalAmount)}/><Metric label="Топливо" value={`${numeric.format(totals.totalLiters)} л`}/><Metric label="Цена за литр" value={totals.averagePrice?`${numeric.format(totals.averagePrice)} ₽`:'—'}/><Metric label="Расход" value={totals.consumption?`${numeric.format(totals.consumption)} л/100 км`:'—'}/><Metric label="Заправок" value={String(totals.count)}/></section><ExpenseChart items={chosen}/></>}</>}
 {screen==='profile'&&<section className="profile"><h2>Мои АЗС</h2><p className="subtext">Названия доступны для выбора в форме заправки.</p><div className="station-add"><input value={stationName} onChange={e=>setStationName(e.target.value)} placeholder="Например, Лукойл"/><button onClick={saveStation}>{editingStation?'Сохранить':'Добавить'}</button>{editingStation&&<button className="secondary compact" onClick={()=>{setEditingStation(null);setStationName('')}}>Отмена</button>}</div><div className="station-list">{stations.map(station=><div key={station.id}><span>{station.name}</span><button onClick={()=>{setEditingStation(station);setStationName(station.name)}}>Изменить</button><button className="remove" onClick={async()=>{if(confirm(`Удалить «${station.name}» из списка?`)){await storage.deleteStation(station.id);await refresh()}}}>Удалить</button></div>)}</div><hr/><h2>Резервная копия</h2><p className="subtext">Экспортируйте данные перед очисткой браузера или переносом на другое устройство.</p><div className="backup"><button onClick={exportBackup}>Скачать копию</button><button className="secondary" onClick={()=>importRef.current?.click()}>Восстановить копию</button><input ref={importRef} type="file" accept="application/json" hidden onChange={e=>importBackup(e.target.files?.[0])}/></div></section>}
 <nav aria-label="Навигация">{([['home','Главная'],['history','История'],['stats','Статистика'],['profile','Профиль']] as [Screen,string][]).map(([key,label])=><button key={key} className={screen===key?'selected':''} onClick={()=>setScreen(key)}>{label}</button>)}</nav>{screen!=='profile'&&<button className="add" onClick={()=>setEditor({draft:newDraft()})}>＋ Добавить заправку</button>}
 {editor&&<Editor value={editor} stations={stations} hintMileage={latestMileage} onChange={setEditor} onSave={save} onCancel={()=>setEditor(null)} onDelete={remove}/>} {notice&&<div className="toast" role="status">{notice}</div>}</main>
}
function Editor({value,stations,hintMileage,onChange,onSave,onCancel,onDelete}:{value:NonNullable<Editor>;stations:Station[];hintMileage?:number;onChange:(x:Editor)=>void;onSave:(e:FormEvent)=>void;onCancel:()=>void;onDelete:(x:Refueling)=>void}){const d=value.draft;const update=<K extends keyof Draft>(key:K,v:Draft[K])=>onChange({...value,draft:{...d,[key]:v}});return <div className="backdrop" role="presentation"><form className="modal" onSubmit={onSave} aria-modal="true" aria-label="Форма заправки"><div className="modal-title"><h2>{value.id?'Изменить заправку':'Новая заправка'}</h2><button type="button" className="icon-button" onClick={onCancel} aria-label="Закрыть">×</button></div><div className="form-grid"><Field label="Цена за литр, ₽" value={d.pricePerLiter||''} type="number" min="0.01" step="0.01" required onChange={v=>update('pricePerLiter',Number(v))}/><Field label="Литры" value={d.liters||''} type="number" min="0.01" step="0.01" required onChange={v=>update('liters',Number(v))}/><label>Сумма, ₽<input value={amount(d)?amount(d).toFixed(2):''} readOnly className="calculated" placeholder="Рассчитывается автоматически"/></label><label>Тип топлива<select value={d.fuelType} onChange={e=>update('fuelType',e.target.value as any)}>{fuels.map(x=><option key={x}>{x}</option>)}</select></label><label>АЗС<input list="stations" value={d.station} onChange={e=>update('station',e.target.value)} placeholder="Выберите или введите"/><datalist id="stations">{stations.map(x=><option key={x.id} value={x.name}/>)}</datalist></label><Field label="Пробег, км" value={d.mileage??''} type="number" min="0" placeholder={hintMileage!==undefined&&!value.id?`Предыдущий: ${numeric.format(hintMileage)} км`:''} onChange={v=>update('mileage',inputNumber(v))}/><Field label="Остаток хода, км" value={d.remainingRange??''} type="number" min="0" onChange={v=>update('remainingRange',inputNumber(v))}/><label>Дата<input type="date" value={d.date} onChange={e=>update('date',e.target.value)} required/></label></div>{value.id&&<button type="button" className="delete" onClick={()=>onDelete({...d,id:value.id!,createdAt:0,updatedAt:0})}>Удалить заправку</button>}<div className="actions"><button type="button" className="secondary" onClick={onCancel}>Отмена</button><button type="submit">Сохранить</button></div></form></div>}
type FieldProps={label:string;value:string|number;onChange:(value:string)=>void}&Omit<React.InputHTMLAttributes<HTMLInputElement>,'value'|'onChange'>;function Field({label,value,onChange,...props}:FieldProps){return <label>{label}<input value={value} onChange={e=>onChange(e.target.value)} {...props}/></label>}
function FuelCard({item,comparison,onClick}:{item:Refueling;comparison?:ReturnType<typeof comparisons> extends Map<string,infer T>?T:never;onClick:()=>void}){const change=(v?:number,u='')=>v===undefined?'':`${v>0?'↑ +':v<0?'↓ ':'= '}${numeric.format(v)}${u}`;return <button className="fuel-card" onClick={onClick}><span className="fuel-icon">⛽</span><span className="card-main"><b>{item.station||'Заправка'}</b><small>{dateText(item.date)} · {item.fuelType}</small>{comparison?.distance!==undefined&&<small className="comparison">{numeric.format(comparison.distance)} км · {numeric.format(comparison.consumption!)} л/100 км ({change(comparison.consumptionDelta,' л/100 км')})</small>}{comparison?.priceDelta!==undefined&&<small className={comparison.priceDelta>0?'bad':'good'}>Цена: {change(comparison.priceDelta,' ₽/л')}</small>}</span><span className="card-value"><b>{rubles.format(amount(item))}</b><small>{numeric.format(item.liters)} л · {numeric.format(item.pricePerLiter)} ₽/л</small></span></button>}
function ExpenseChart({items}:{items:Refueling[]}){const data=useMemo(()=>{const days=new Map<string,number>();items.forEach(x=>days.set(x.date,(days.get(x.date)||0)+amount(x)));const max=Math.max(...days.values(),1);return [...days.entries()].sort().map(([date,value])=>({date,value,height:value/max*100}))},[items]);return <section className="chart"><h2>Расходы по дням</h2>{data.length?<div className="bars">{data.map(x=><div key={x.date} className="bar-wrap" title={`${dateText(x.date)}: ${rubles.format(x.value)}`}><div className="bar" style={{height:`${x.height}%`}}/><small>{x.date.slice(8)}</small></div>)}</div>:<p className="subtext">Нет заправок за выбранный период.</p>}</section>}
function Empty({onAdd}:{onAdd:()=>void}){return <section className="empty"><div>⛽</div><h2>Заправок пока нет</h2><p>Добавьте первую запись, чтобы видеть расходы и расход топлива.</p><button onClick={onAdd}>Добавить заправку</button></section>};function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>};createRoot(document.getElementById('root')!).render(<App />)
