import React, { FormEvent, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BarChart, Bar, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import './styles.css'

type FuelType = 'АИ-92' | 'АИ-95' | 'АИ-98' | 'АИ-100' | 'ДТ' | 'Газ'
type Refueling = { id: string; liters: number; fuelType: FuelType; station: string; pricePerLiter: number; mileage?: number; remainingRange?: number; date: string }
type Draft = Omit<Refueling, 'id'>
type Comparison = { distance?: number; consumption?: number; priceDelta?: number; amountDelta?: number; consumptionDelta?: number }
const DB_KEY = 'fuel-tracker.refuelings.v2'
const OLD_DB_KEY = 'fuel-tracker.refuelings.v1'
const STATIONS_KEY = 'fuel-tracker.stations.v1'
const fuels: FuelType[] = ['АИ-92', 'АИ-95', 'АИ-98', 'АИ-100', 'ДТ', 'Газ']
const money = new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB', maximumFractionDigits: 0 })
const number = new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 2 })
const today = () => new Date().toISOString().slice(0, 10)
const amount = (item: Pick<Refueling, 'liters' | 'pricePerLiter'>) => item.liters * item.pricePerLiter
const readRefuelings = (): Refueling[] => { try { const current = localStorage.getItem(DB_KEY); if (current) return JSON.parse(current); const old = JSON.parse(localStorage.getItem(OLD_DB_KEY) || '[]'); return old.map((x: any) => ({ id:x.id, liters:x.liters, fuelType:x.fuelType, station:x.station || '', pricePerLiter:x.pricePerLiter || (x.liters ? x.amount / x.liters : 0), mileage:x.mileage, remainingRange:x.fuelLevel, date:(x.date || today()).slice(0,10) })) } catch { return [] } }
const readStations = (): string[] => { try { return JSON.parse(localStorage.getItem(STATIONS_KEY) || '[]') } catch { return [] } }
const emptyDraft = (hint?: number): Draft => ({ liters: 0, fuelType: 'АИ-95', station: '', pricePerLiter: 0, mileage: undefined, remainingRange: undefined, date: today() })
const dateLabel = (value: string) => new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${value}T12:00:00`))
const dayKey = (value: string) => new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: '2-digit' }).format(new Date(`${value}T12:00:00`))
const ordered = (items: Refueling[]) => [...items].sort((a,b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id))
function comparisons(items: Refueling[]) { const map = new Map<string, Comparison>(); const list = ordered(items); for (let i=1;i<list.length;i++) { const prev=list[i-1], current=list[i]; const distance = current.mileage !== undefined && prev.mileage !== undefined ? current.mileage-prev.mileage : undefined; const consumption = distance && distance>0 ? current.liters/distance*100 : undefined; const priorDistance = i>1 && prev.mileage !== undefined && list[i-2].mileage !== undefined ? prev.mileage-list[i-2].mileage : undefined; const priorConsumption = priorDistance && priorDistance>0 ? prev.liters/priorDistance*100 : undefined; map.set(current.id,{ distance: distance && distance>0 ? distance : undefined, consumption, priceDelta:current.pricePerLiter-prev.pricePerLiter, amountDelta:amount(current)-amount(prev), consumptionDelta: consumption !== undefined && priorConsumption !== undefined ? consumption-priorConsumption : undefined }) } return map }
function App() {
 const [items,setItems]=useState<Refueling[]>(readRefuelings), [stations,setStations]=useState<string[]>(readStations), [screen,setScreen]=useState<'home'|'history'|'stats'|'profile'>('home'), [editor,setEditor]=useState<{id?:string;draft:Draft}|null>(null), [toast,setToast]=useState(''), [period,setPeriod]=useState<'week'|'month'|'year'|'custom'>('month'), [start,setStart]=useState(''), [end,setEnd]=useState(''), [newStation,setNewStation]=useState('')
 useEffect(()=>localStorage.setItem(DB_KEY,JSON.stringify(items)),[items]); useEffect(()=>localStorage.setItem(STATIONS_KEY,JSON.stringify(stations)),[stations])
 const sorted=useMemo(()=>ordered(items).reverse(),[items]), compare=useMemo(()=>comparisons(items),[items]); const latestMileage=useMemo(()=>ordered(items).filter(x=>x.mileage!==undefined).at(-1)?.mileage,[items])
 const visible=useMemo(()=>{ const now=new Date(); if(period==='custom'){const low=start?new Date(start+'T00:00:00'):new Date(0),high=end?new Date(end+'T23:59:59'):new Date(8640000000000000);return sorted.filter(x=>{const d=new Date(x.date+'T12:00:00');return d>=low&&d<=high})} const from=new Date(now);if(period==='week')from.setDate(now.getDate()-6);if(period==='month')from.setDate(1);if(period==='year')from.setMonth(0,1);from.setHours(0,0,0,0);return sorted.filter(x=>new Date(x.date+'T12:00:00')>=from)},[sorted,period,start,end])
 const month=useMemo(()=>{const n=new Date();return sorted.filter(x=>{const d=new Date(x.date+'T12:00:00');return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()})},[sorted]); const usage=(list:Refueling[])=>{const values=[...comparisons(list).values()].map(x=>x.consumption).filter((x):x is number=>x!==undefined);return values.length?values.reduce((s,x)=>s+x,0)/values.length:undefined}; const sums=(list:Refueling[])=>({amount:list.reduce((s,x)=>s+amount(x),0),liters:list.reduce((s,x)=>s+x.liters,0),usage:usage(list)}); const monthSum=sums(month), selected=sums(visible)
 const openNew=()=>setEditor({draft:emptyDraft(latestMileage)}); const update=<K extends keyof Draft>(key:K,value:Draft[K])=>setEditor(x=>x?{...x,draft:{...x.draft,[key]:value}}:x)
 const submit=(e:FormEvent)=>{e.preventDefault();if(!editor)return;const d=editor.draft;if(d.pricePerLiter<=0||d.liters<=0){setToast('Введите цену и количество литров');return}const record:Refueling={...d,id:editor.id||crypto.randomUUID()};setItems(xs=>editor.id?xs.map(x=>x.id===editor.id?record:x):[...xs,record]);if(d.station.trim()&&!stations.includes(d.station.trim()))setStations(xs=>[...xs,d.station.trim()].sort((a,b)=>a.localeCompare(b,'ru')));setEditor(null);setToast(editor.id?'Заправка изменена':'Заправка добавлена');setTimeout(()=>setToast(''),2400)}
 const addStation=()=>{const name=newStation.trim();if(name&&!stations.includes(name)){setStations(x=>[...x,name].sort((a,b)=>a.localeCompare(b,'ru')));setNewStation('')} }; const renameStation=(name:string)=>{const next=prompt('Новое название АЗС',name)?.trim();if(next&&next!==name){setStations(xs=>xs.map(x=>x===name?next:x));setItems(xs=>xs.map(x=>x.station===name?{...x,station:next}:x))}}
 return <main><header><div><p className="eyebrow">Личный учёт</p><h1>{screen==='home'?'Топливный учёт':screen==='history'?'История':screen==='stats'?'Статистика':'Профиль'}</h1></div><button className="icon-button" onClick={()=>setScreen('profile')} aria-label="Профиль">⚙</button></header>
 {screen==='home'&&<><section className="summary"><p>Текущий месяц</p><strong>{money.format(monthSum.amount)}</strong><div><span>{number.format(monthSum.liters)} л</span><span>{monthSum.usage?`${number.format(monthSum.usage)} л/100 км`:'Расход: —'}</span></div></section><section className="section-title"><h2>Последние заправки</h2><button className="text-button" onClick={()=>setScreen('history')}>Все</button></section>{sorted.length?<div className="list">{sorted.slice(0,5).map(x=><FuelCard key={x.id} item={x} comparison={compare.get(x.id)} onClick={()=>setEditor({id:x.id,draft:{...x}})}/>)}</div>:<Empty onAdd={openNew}/>}</>}
 {screen==='history'&&<><p className="subtext">Всего записей: {sorted.length}</p>{sorted.length?<div className="list">{sorted.map(x=><FuelCard key={x.id} item={x} comparison={compare.get(x.id)} onClick={()=>setEditor({id:x.id,draft:{...x}})}/>)}</div>:<Empty onAdd={openNew}/>}</>}
 {screen==='stats'&&<><div className="filters">{(['week','month','year','custom'] as const).map(x=><button key={x} className={period===x?'active':''} onClick={()=>setPeriod(x)}>{({week:'Неделя',month:'Месяц',year:'Год',custom:'Период'})[x]}</button>)}</div>{period==='custom'&&<div className="dates"><label>С<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>По<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>}{start&&end&&end<start&&<p className="error">Дата окончания не может быть раньше даты начала.</p>}<section className="metric-grid"><Metric label="Расходы" value={money.format(selected.amount)}/><Metric label="Топливо" value={`${number.format(selected.liters)} л`}/><Metric label="Цена за литр" value={selected.liters?`${number.format(selected.amount/selected.liters)} ₽`:'—'}/><Metric label="Расход" value={selected.usage?`${number.format(selected.usage)} л/100 км`:'—'}/><Metric label="Заправок" value={String(visible.length)}/></section><section className="chart"><h2>Расходы по дням</h2>{visible.length?<ResponsiveContainer width="100%" height={220}><BarChart data={Object.values(visible.reduce<Record<string,{day:string;value:number}>>((a,x)=>{const k=dayKey(x.date);a[k]||={day:k,value:0};a[k].value+=amount(x);return a},{}))}><XAxis dataKey="day"/><YAxis hide/><Tooltip/><Bar dataKey="value" fill="#0d8a68" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer>:<p className="subtext">Нет заправок за выбранный период.</p>}</section></>}
 {screen==='profile'&&<section className="profile"><h2>Мои АЗС</h2><p className="subtext">Сохранённые названия доступны в форме заправки.</p><div className="station-add"><input value={newStation} onChange={e=>setNewStation(e.target.value)} placeholder="Например, Лукойл"/><button onClick={addStation}>Добавить</button></div>{stations.length?<div className="station-list">{stations.map(x=><div key={x}><span>{x}</span><button onClick={()=>renameStation(x)}>Изменить</button><button className="remove" onClick={()=>{if(confirm(`Удалить «${x}» из списка?`))setStations(xs=>xs.filter(y=>y!==x))}}>Удалить</button></div>)}</div>:<p className="subtext">Список АЗС пока пуст.</p>}</section>}
 <nav><button className={screen==='home'?'selected':''} onClick={()=>setScreen('home')}>Главная</button><button className={screen==='history'?'selected':''} onClick={()=>setScreen('history')}>История</button><button className={screen==='stats'?'selected':''} onClick={()=>setScreen('stats')}>Статистика</button><button className={screen==='profile'?'selected':''} onClick={()=>setScreen('profile')}>Профиль</button></nav>{screen!=='profile'&&<button className="add" onClick={openNew}>＋ Добавить заправку</button>}
 {editor&&<div className="backdrop"><form className="modal" onSubmit={submit}><div className="modal-title"><h2>{editor.id?'Изменить заправку':'Новая заправка'}</h2><button type="button" className="icon-button" onClick={()=>setEditor(null)}>×</button></div><div className="form-grid"><Field label="Цена за литр, ₽" value={editor.draft.pricePerLiter||''} type="number" step="0.01" required onChange={v=>update('pricePerLiter',Number(v))}/><Field label="Литры" value={editor.draft.liters||''} type="number" step="0.01" required onChange={v=>update('liters',Number(v))}/><label>Сумма, ₽<input value={amount(editor.draft)?amount(editor.draft).toFixed(2):''} readOnly className="calculated" placeholder="Рассчитывается автоматически"/></label><label>Тип топлива<select value={editor.draft.fuelType} onChange={e=>update('fuelType',e.target.value as FuelType)}>{fuels.map(x=><option key={x}>{x}</option>)}</select></label><label>АЗС<input list="stations" value={editor.draft.station} onChange={e=>update('station',e.target.value)} placeholder="Выберите или введите"/><datalist id="stations">{stations.map(x=><option key={x} value={x}/>)}</datalist></label><Field label="Пробег, км" value={editor.draft.mileage??''} type="number" placeholder={latestMileage!==undefined&&!editor.id?`Предыдущий: ${number.format(latestMileage)} км`:''} onChange={v=>update('mileage',v===''?undefined:Number(v))}/><Field label="Остаток хода, км" value={editor.draft.remainingRange??''} type="number" onChange={v=>update('remainingRange',v===''?undefined:Number(v))}/><label>Дата<input type="date" value={editor.draft.date} onChange={e=>update('date',e.target.value)} required/></label></div>{editor.id&&<button type="button" className="delete" onClick={()=>{if(confirm('Удалить эту заправку?')){setItems(xs=>xs.filter(x=>x.id!==editor.id));setEditor(null);setToast('Заправка удалена')}}>Удалить заправку</button>}<div className="actions"><button type="button" className="secondary" onClick={()=>setEditor(null)}>Отмена</button><button type="submit">Сохранить</button></div></form></div>}{toast&&<div className="toast">{toast}</div>}</main>
}
type FieldProps={label:string;value:string|number;onChange:(value:string)=>void}&Omit<React.InputHTMLAttributes<HTMLInputElement>,'value'|'onChange'>
function Field({label,value,onChange,...props}:FieldProps){return <label>{label}<input value={value} onChange={e=>onChange(e.target.value)} {...props}/></label>}
function FuelCard({item,comparison,onClick}:{item:Refueling;comparison?:Comparison;onClick:()=>void}){const lines=[comparison?.distance!==undefined?`Пробег: ${number.format(comparison.distance)} км`:null,comparison?.consumption!==undefined?`Расход: ${number.format(comparison.consumption)} л/100 км${delta(comparison.consumptionDelta,' л/100 км')}`:null,comparison?.priceDelta!==undefined?`Цена: ${delta(comparison.priceDelta,' ₽/л')}`:null].filter(Boolean);return <button className="fuel-card" onClick={onClick}><span className="fuel-icon">⛽</span><span className="card-main"><b>{item.station||'Заправка'}</b><small>{dateLabel(item.date)} · {item.fuelType}</small>{lines.length>0&&<small className="comparison">{lines.join(' · ')}</small>}</span><span className="card-value"><b>{money.format(amount(item))}</b><small>{number.format(item.liters)} л · {number.format(item.pricePerLiter)} ₽/л</small></span></button>}
function delta(value:number|undefined,unit:string){if(value===undefined)return '';const sign=value>0?'↑ +':value<0?'↓ ': '= ';return ` (${sign}${number.format(value)}${unit})`}
function Empty({onAdd}:{onAdd:()=>void}){return <section className="empty"><div>⛽</div><h2>Заправок пока нет</h2><p>Добавьте первую запись, чтобы видеть расходы и расход топлива.</p><button onClick={onAdd}>Добавить заправку</button></section>};function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>};createRoot(document.getElementById('root')!).render(<App />)
