import { Refueling, Station } from './domain'
const DB = 'fuel-tracker'; const VERSION = 1; const LEGACY_RECORDS_V2 = 'fuel-tracker.refuelings.v2'; const LEGACY_RECORDS_V1 = 'fuel-tracker.refuelings.v1'; const LEGACY_STATIONS = 'fuel-tracker.stations.v1'
function openDb(): Promise<IDBDatabase> { return new Promise((resolve,reject) => { const request=indexedDB.open(DB,VERSION); request.onupgradeneeded=()=>{const db=request.result; if(!db.objectStoreNames.contains('refuelings')) db.createObjectStore('refuelings',{keyPath:'id'}); if(!db.objectStoreNames.contains('stations')) db.createObjectStore('stations',{keyPath:'id'})}; request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error) }) }
async function all<T>(store:string):Promise<T[]> { const db=await openDb(); return new Promise((resolve,reject)=>{const request=db.transaction(store,'readonly').objectStore(store).getAll();request.onsuccess=()=>resolve(request.result as T[]);request.onerror=()=>reject(request.error)}) }
async function put<T>(store:string,value:T){const db=await openDb();return new Promise<void>((resolve,reject)=>{const request=db.transaction(store,'readwrite').objectStore(store).put(value);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
async function remove(store:string,id:string){const db=await openDb();return new Promise<void>((resolve,reject)=>{const request=db.transaction(store,'readwrite').objectStore(store).delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
function parsed(key:string):any[]{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}
function legacyRecords():Refueling[]{const source=parsed(LEGACY_RECORDS_V2).length?parsed(LEGACY_RECORDS_V2):parsed(LEGACY_RECORDS_V1);return source.filter(x=>x&&x.id).map((x:any,index:number)=>({id:String(x.id),createdAt:Number(x.createdAt)||Date.now()-source.length+index,updatedAt:Number(x.updatedAt)||Date.now(),date:String(x.date||new Date().toISOString().slice(0,10)).slice(0,10),liters:Number(x.liters)||0,pricePerLiter:Number(x.pricePerLiter)||(Number(x.liters)?Number(x.amount)/Number(x.liters):0),fuelType:x.fuelType||'АИ-95',station:String(x.station||''),mileage:x.mileage===undefined?undefined:Number(x.mileage),remainingRange:x.remainingRange===undefined?(x.fuelLevel===undefined?undefined:Number(x.fuelLevel)):Number(x.remainingRange)}))}
export const storage={ refuelings:()=>all<Refueling>('refuelings'), stations:()=>all<Station>('stations'), saveRefueling:(value:Refueling)=>put('refuelings',value), deleteRefueling:(id:string)=>remove('refuelings',id), saveStation:(value:Station)=>put('stations',value), deleteStation:(id:string)=>remove('stations',id), async migrateLegacy(){const existing=await all<Refueling>('refuelings');if(existing.length)return;const records=legacyRecords();const names=[...new Set([...parsed(LEGACY_STATIONS),...records.map(x=>x.station).filter(Boolean)].map((x:any)=>String(x).trim()).filter(Boolean))];await Promise.all([...records.map(record=>put('refuelings',record)),...names.map((name,index)=>put('stations',{id:`legacy-station-${index}`,name} as Station))])}, async backup(){return {version:1, exportedAt:new Date().toISOString(), refuelings:await all<Refueling>('refuelings'), stations:await all<Station>('stations')}}, async restore(data:any){if(!data||!Array.isArray(data.refuelings)||!Array.isArray(data.stations))throw new Error('Некорректный файл резервной копии.');await Promise.all([...data.refuelings.map((x:Refueling)=>put('refuelings',x)),...data.stations.map((x:Station)=>put('stations',x))])} }
